echo "deleting profiles you we dont manage globally"
[ -f "repo/profiles/System Administrator with Deferred Sharing.profile" ] && rm "repo/profiles/System Administrator with Deferred Sharing.profile"
[ -f "repo/profiles/PILOT - SE - Fielo Admin.profile" ] && rm "repo/profiles/PILOT - SE - Fielo Admin.profile"
[ -f "repo/profiles/SE - Case Archive.profile" ] && rm "repo/profiles/SE - Case Archive.profile"
[ -f "repo/profiles/SE - Performance User.profile" ] && rm "repo/profiles/SE - Performance User.profile"
[ -f "repo/profiles/Connect Basic Users.profile" ] && rm "repo/profiles/Connect Basic Users.profile"
[ -f "repo/profiles/DMT - User with Budget visibility.profile" ] && rm "repo/profiles/DMT - User with Budget visibility.profile"
[ -f "repo/profiles/SE - Interface - PRM Program Management Connector.profile" ] && rm "repo/profiles/SE - Interface - PRM Program Management Connector.profile"
[ -f "repo/profiles/ContractManager.profile" ] && rm "repo/profiles/ContractManager.profile"
[ -f "repo/profiles/MarketingProfile.profile" ] && rm "repo/profiles/MarketingProfile.profile"
[ -f "repo/profiles/ReadOnly.profile" ] && rm "repo/profiles/ReadOnly.profile"
[ -f "repo/profiles/SE - Rewards External Agent.profile" ] && rm "repo/profiles/SE - Rewards External Agent.profile"
[ -f "repo/profiles/SolutionManager.profile" ] && rm "repo/profiles/SolutionManager.profile"
[ -f "repo/profiles/Standard.profile" ] && rm "repo/profiles/Standard.profile"
[ -f "repo/profiles/StandardAul.profile" ] && rm "repo/profiles/StandardAul.profile"
[ -f "repo/profiles/Premier Support User.profile" ] && rm "repo/profiles/Premier Support User.profile"
[ -f "repo/profiles/Force%2Ecom - App Subscription User.profile" ] && rm "repo/profiles/Force%2Ecom - App Subscription User.profile"
[ -f "repo/profiles/Company Communities User.profile" ] && rm "repo/profiles/Company Communities User.profile"
[ -f "repo/profiles/Customer Community Plus User.profile" ] && rm "repo/profiles/Customer Community Plus User.profile"
[ -f "repo/profiles/Gold Partner User.profile" ] && rm "repo/profiles/Gold Partner User.profile"
[ -f "repo/profiles/Chatter External User.profile" ] && rm "repo/profiles/Chatter External User.profile"
[ -f "repo/profiles/Fielo Member Site.profile" ] && rm "repo/profiles/Fielo Member Site.profile"
[ -f "repo/profiles/Chatter Free User.profile" ] && rm "repo/profiles/Chatter Free User.profile"
[ -f "repo/profiles/Chatter Moderator User.profile" ] && rm "repo/profiles/Chatter Moderator User.profile"
[ -f "repo/profiles/Customer Portal Manager Custom.profile" ] && rm "repo/profiles/Customer Portal Manager Custom.profile"
[ -f "repo/profiles/High Volume Customer Portal User.profile" ] && rm "repo/profiles/High Volume Customer Portal User.profile"
[ -f "repo/profiles/Authenticated Website.profile" ] && rm "repo/profiles/Authenticated Website.profile"
[ -f "repo/profiles/Fielo Profile.profile" ] && rm "repo/profiles/Fielo Profile.profile"
[ -f "repo/profiles/Customer Community Login User.profile" ] && rm "repo/profiles/Customer Community Login User.profile"
[ -f "repo/profiles/Customer Community User.profile" ] && rm "repo/profiles/Customer Community User.profile"
[ -f "repo/profiles/Identity Profile1466911959685.profile" ] && rm "repo/profiles/Identity Profile1466911959685.profile"
[ -f "repo/profiles/Partner Community Login User.profile" ] && rm "repo/profiles/Partner Community Login User.profile"
[ -f "repo/profiles/Partner Community User %28Identity%29.profile" ] && rm "repo/profiles/Partner Community User %28Identity%29.profile"
[ -f "repo/profiles/Partner Community User.profile" ] && rm "repo/profiles/Partner Community User.profile"
[ -f "repo/profiles/Cassini Profile1466910799067.profile" ] && rm "repo/profiles/Cassini Profile1466910799067.profile"
[ -f "repo/profiles/Compass Community Profile.profile" ] && rm "repo/profiles/Compass Community Profile.profile"
[ -f "repo/profiles/Compass Profile.profile" ] && rm "repo/profiles/Compass Profile.profile"
[ -f "repo/profiles/ELLA Profile.profile" ] && rm "repo/profiles/ELLA Profile.profile"
[ -f "repo/profiles/Guest License User.profile" ] && rm "repo/profiles/Guest License User.profile"
[ -f "repo/profiles/Lesser Panda Community Profile.profile" ] && rm "repo/profiles/Lesser Panda Community Profile.profile"
[ -f "repo/profiles/LoyaltyRedirect Profile.profile" ] && rm "repo/profiles/LoyaltyRedirect Profile.profile"
[ -f "repo/profiles/SE - DMT Advanced User %28Force%2Ecom%29.profile" ] && rm "repo/profiles/SE - DMT Advanced User %28Force%2Ecom%29.profile"
[ -f "repo/profiles/SE - DMT Standard User %28Force%2Ecom%29.profile" ] && rm "repo/profiles/SE - DMT Standard User %28Force%2Ecom%29.profile"
[ -f "repo/profiles/Salesforce Identity Login Widget Profile.profile" ] && rm "repo/profiles/Salesforce Identity Login Widget Profile.profile"
[ -f "repo/profiles/demo Profile.profile" ] && rm "repo/profiles/demo Profile.profile"
echo 'deleting previous backups of compressed files'
rm -rf repo/profiles/*.bak repo/permissionsets/*.bak repo/labels/*.bak
echo 'starting to compress the xml files, it saves space and reduces conflict for others'
echo 'Fair warning before I begin, its gonna take atleast 40-50 seconds on a mac, may be around 3 minutes on windows'
time perl -i.bak -p scripts/profileCompress.pl repo/profiles/*.profile repo/permissionsets/*.permissionset repo/labels/*.labels repo/objects/*.object
echo 'we finished generating compressed files, lets delete the .bak files, you wont need them'
rm -rf repo/profiles/*.bak repo/permissionsets/*.bak repo/labels/*.bak